#!/usr/bin/python3
def raise_exception_msg():
    value = "Hello"
    try:
        print(val)
    except NameError:
        print("C is fun")
    pass


def main():
    raise_exception_msg()
    pass


if __name__ == "__main__":
    main()
    pass
